### ISSUE TITLE
Add VPR scoring to findings.csv

### ISSUE THREAD

**Issue by jeffkause** [cisagov/cyhy-system#103]
# 💡 Summary #

Add VPR scoring to findings.csv for ad-hoc alerts and main VS reports

## Motivation and context ##

The stakeholder needs to be aware of the VPR score.

## Implementation notes ##

Add VPR column to findings.csv

## Acceptance criteria ##

- [x] New VPR column added to findings.csv file in ad-hoc report
- [x] New VPR column added to findings.csv file in main VS report

**Comment by KeithBonesJr** [comment]
@jeffkause is this issue good to close?

**Comment by KeithBonesJr** [comment]
Changes have been verified.
