### ISSUE TITLE
Remove FTP from BOD 23-02 Scope

### ISSUE THREAD

**Issue by KeithBonesJr** [cisagov/cyhy-system#108]
# 💡 Summary #

Remove FTP from the scope of BOD 23-02

## Motivation and context ##

File Transfer Protocol (FTP)

The service itself - does not function as a method for connecting to an NMI, but the FTP default port could be configured to do so (e.g. SSH running on port 21).

Because CyHy VS flags the service, CyHy will stop flagging/reporting FTP as potential NMI instances. The CyberDirectives and Cyber Hygiene teams believes this provides better accuracy and lowers the NMI reporting/tracking level of effort

CyHy messaging around risky services (FTP included) will continue in weekly and ad-hoc alerts, but it will no longer be connected directly with BOD 23-02 reporting requirements.

## Implementation notes ##

The following updates need to be made

- Remove asterisks for "FTP" on report card within the Potentially Risky Open Services on VS main report
- Remove FTP from NMI count on VS main report
- Change possible NMI to FALSE when detected for the potentially risky services attachment within the VS main report and ad-hoc alerts
- Remove red from ftp services on ad-hoc alerts
- Remove red and asterisks for category on ad-hoc 

## Acceptance criteria ##

- [x] FTP listed on "Potentially Risky Open Services" on VS main report with no asterisks
- [x] FTP is not factored into the NMI count on VS main report (fed and non-fed)
- [x] The "Possible NMI" column within the potentially risky services attachment should say FALSE when FTP is flagged for the main VS report
- [x] The "Possible NMI" column within the potentially risky services attachment should say FALSE when FTP is flagged for the ad-hoc alerts
- [x] The ftp services  displayed in black for the table within the ad-hoc alerts when FTP is flagged
- [x] The ftp category displayed in black with no asterisks for the table within the ad-hoc alerts table when FTP is flagged

**Comment by dav3r** [comment]
This should just be a matter of removing "ftp" from the list of `POTENTIAL_NMI_SERVICES` [here](https://github.com/cisagov/cyhy-reports/blob/57e67d7f336fb215d0f8ed7e861e51fc32c3a01b/cyhy_report/customer/generate_report.py#L185-L196) and [here](https://github.com/cisagov/cyhy-reports/blob/57e67d7f336fb215d0f8ed7e861e51fc32c3a01b/cyhy_report/cyhy_notification/generate_notification.py#L127-L138).

**Comment by KeithBonesJr** [comment]
[heart]         Bones, Keith (CTR) reacted to your message:
________________________________
