### ISSUE TITLE
Remove the BCC: line for the CSA emails from weekly CyHy reports and daily notifications for entities in the CSAs' regions

### ISSUE THREAD

**Issue by jeffkause** [cisagov/cyhy-system#129]
# 💡 Summary #

The CISA Cyber Security Advisors (CSAs) would like to be removed from receiving the CyHy reports and daily notifications for the entities in their regions. This is a reversal of https://github.com/cisagov/cyhy-system/issues/114

## Motivation and context ##

The CSAs no longer wish to receive CyHy reports and notifications. They will look up the information as needed.

## Implementation notes ##

• Remove all CSA region emails for the BCC: line of the CyHy weekly reports and notifications, rolling back Issue #114.

## Acceptance criteria ##

- [x] CISA regional CSAs would not be receiving weekly CyHy reports for their entities.
- [x] CISA regional CSAs would not be receiving daily or ad-hoc CyHy reports for their entities.

**Comment by dav3r** [comment]
Please have a Fed lead confirm (via a comment on this issue) that this change has been approved.  Thanks!

**Comment by MegsG** [comment]
> Please have a Fed lead confirm (via a comment on this issue) that this change has been approved. Thanks!

Good morning, the federal team is approving this request, thank you!

**Comment by MegsG** [comment]
> Please have a Fed lead confirm (via a comment on this issue) that this change has been approved. Thanks!

Clicked the wrong button of course. Hello folks, posting this as the federal approval for this issue, thank you!

**Comment by dav3r** [comment]
The following PRs (once approved, merged, and deployed) will resolve this issue:
* https://github.com/cisagov/cyhy-mailer/pull/117
* https://github.com/cisagov/cyhy_amis/pull/846

**Comment by dav3r** [comment]
Both https://github.com/cisagov/cyhy-mailer/pull/117 and https://github.com/cisagov/cyhy_amis/pull/846 have been merged and deployed.

@jeffkause and/or @MegsG - Please confirm that the CSAs did not receive any daily notification emails this morning.
