### ISSUE TITLE
Generate notification docs for new tickets with KEV CVEs

### ISSUE THREAD

**Issue by chelsgr** [cisagov/cyhy-system#41]
## Task ##

In support of BOD 22-01 requirements 5 & 6: Generate notification docs for new tickets with KEV CVEs

## Comments ##

- Changes to be made here: https://github.com/cisagov/cyhy-core/blob/develop/cyhy/db/ticket_manager.py#L247-L249

### References ###

- Epic https://github.com/cisagov/cool-system-internal/issues/107
- Story #29 
- Current Estimated LOE: Approximately 2 hours.

**Comment by felddy** [comment]
Closed by: cisagov/cyhy-core#63
