### ISSUE TITLE
Generate notification docs for existing tickets

### ISSUE THREAD

**Issue by chelsgr** [cisagov/cyhy-system#42]
## Task ##

In support of BOD 22-01 requirement 13: Generate notification docs for existing tickets with newly discovered KEV CVEs, as well as when an existing CVE severity increases from low/moderate to high/critical.

## Objectives ##

- [ ] Send notification when non-KEV tickets become KEVs (the next time the ticket is processed after the list of KEVs is updated)
- [ ] Send notification when non-Critical/High tickets become Critical/High (the next time the ticket is processed after the list of NVD CVEs is updated)

### References ###

- Epic https://github.com/cisagov/cool-system-internal/issues/107
- Story #29 
- Current Estimated LOE: TBD for both objectives.

**Comment by dav3r** [comment]
Closed via https://github.com/cisagov/cyhy-core/pull/65
