### ISSUE TITLE
KEV flag will be added to the details section of the TicketDoc

### ISSUE THREAD

**Issue by chelsgr** [cisagov/cyhy-system#43]
## Tasks ##

In support of BOD 22-01 requirement 2: KEV flag will be added to the `details` section of the `TicketDoc`.

## Comments ##

See: https://github.com/cisagov/cyhy-core/blob/develop/cyhy/db/ticket_manager.py#L90

### References ###
- Epic https://github.com/cisagov/cool-system-internal/issues/107
- Story #33 
- Current Estimated LOE: Approximately 2 hours.

**Comment by felddy** [comment]
Closed by: cisagov/cyhy-core#63
