### ISSUE TITLE
Write new query to determine if a host has any KEVs

### ISSUE THREAD

**Issue by chelsgr** [cisagov/cyhy-system#44]
## Tasks ##

In support of BOD 22-01 requirement 14: write new query to determine if a host has any KEVs.

## Comments ##

Similar to [this](https://github.com/cisagov/cyhy-core/blob/79d25173b91c6cd71bd106733f21020c81282e5a/cyhy/db/queries.py#L261-L269)

### References ###
- Epic https://github.com/cisagov/cool-system-internal/issues/107
- Story #38  
- Current Estimated LOE: Approximately 3 hours.

**Comment by felddy** [comment]
Closed by: cisagov/cyhy-core#64
