### ISSUE TITLE
Calculate host scan priority using KEV flag

### ISSUE THREAD

**Issue by chelsgr** [cisagov/cyhy-system#45]
## Tasks ##

In support of requirement 14: Calculate host scan priority using KEV flag.

## Comments ##

Changes occur here `priority_from_kev`: https://github.com/cisagov/cyhy-core/blob/79d25173b91c6cd71bd106733f21020c81282e5a/cyhy/db/scheduler.py#L76

### References ###
- Epic https://github.com/cisagov/cool-system-internal/issues/107
- Story #38 
- Current Estimated LOE: Approximately 2 hours.

**Comment by felddy** [comment]
Closed by: cisagov/cyhy-core#64
