### ISSUE TITLE
Update daily notification template with content changes

### ISSUE THREAD

**Issue by chelsgr** [cisagov/cyhy-system#46]
## Tasks ##

In support of BOD 22-01 requirements 5 and 6: Update daily [notification template](https://github.com/cisagov/cyhy-reports/blob/develop/cyhy_report/cyhy_notification/notification.mustache) with content changes from https://github.com/cisagov/cyhy-system/issues/29

### References ###
- Epic https://github.com/cisagov/cool-system-internal/issues/107
- Story #29 
- Current Estimated LOE: Approximately 3 hours.

**Comment by dav3r** [comment]
Resolved via https://github.com/cisagov/cyhy-reports/pull/69
