### ISSUE TITLE
Modify the weekly report generator script to create two new CSVs instead of current four CSVs

### ISSUE THREAD

**Issue by chelsgr** [cisagov/cyhy-system#49]
## Task ##

In support of BOD 22-01 requirements 10 and 11: Update [create_snapshots_reports_scorecard.py](https://github.com/cisagov/cyhy-reports/blob/develop/extras/create_snapshots_reports_scorecard.py#L747-L777) to only create the 2 new CSVs (and stop creating the previous 4 CSVs).

## Comments ##

The associated CSVs are generated here: https://github.com/cisagov/cyhy-reports/blob/develop/extras/create_snapshots_reports_scorecard.py#L747-L777 

### References ###

- Epic https://github.com/cisagov/cool-system-internal/issues/107
- Story #34 
- Current Estimated LOE: 4 hours for this task.

**Comment by dav3r** [comment]
Resolved via: 
* https://github.com/cisagov/ncats-webd/pull/27
* https://github.com/cisagov/cyhy-reports/pull/72
