### ISSUE TITLE
Update weekly CyHy customer report with KEVs content

### ISSUE THREAD

**Issue by chelsgr** [cisagov/cyhy-system#51]
## Task ##

In support of BOD 22-01 requirements 8 and 9, update [report template](https://github.com/cisagov/cyhy-reports/blob/develop/cyhy_report/customer/report.mustache) with content changes from https://github.com/cisagov/cyhy-reports/issues/68.

### References ###

- Epic https://github.com/cisagov/cool-system-internal/issues/107
- Story https://github.com/cisagov/cyhy-reports/issues/68
- Current Estimated LOE: TBD for this task.

**Comment by king-alexander** [comment]
@dav3r I updated the report template with acronym and glossary entries for KEVs. Want me to open a PR on cyhy-reports?

**Comment by dav3r** [comment]
Thanks @king-alexander, but I already have those changes done- they will be in an upcoming PR.  You can see my work so far in [this branch](https://github.com/cisagov/cyhy-reports/tree/improvement/report-content-bod-22-01).

If you see that an issue is assigned to someone (as this one is), it's always a good idea to check with them before doing any work towards it.

**Comment by dav3r** [comment]
> Thanks @king-alexander, but I already have those changes done- they will be in an upcoming PR. You can see my work so far in [this branch](https://github.com/cisagov/cyhy-reports/tree/improvement/report-content-bod-22-01).

@king-alexander Here's [the draft PR](https://github.com/cisagov/cyhy-reports/pull/71).  I still have more testing to do before it's ready for full review, but feel free to take a look at it and let me know if you spot anything awry.

**Comment by king-alexander** [comment]
Thanks @dav3r! I'll take a look tomorrow morning.

**Comment by king-alexander** [comment]
@dav3r I took a look. Nothing awry to report here 👍.

**Comment by dav3r** [comment]
Resolved via https://github.com/cisagov/cyhy-reports/pull/72.
