### ISSUE TITLE
Modify findings.csv to accommodate CVSSv3.0+ and VPR scoring when available

### ISSUE THREAD

**Issue by chelsgr** [cisagov/cyhy-system#62]
# Summary #

There are three changes requested to the findings.csv file which is attached to VS reports.

1. The cvss_base_score would use the base score provided by the latest CVSS version available,
2. there would be an extra column to denote which CVSS version it is, 
3. and there would be another new column to share the VPR score, when one is associated with that row’s CVE.

## Motivation and context ##

This change is required to support [Modify CyHy VS to include CVSSv3+ and VPR scoring #59](https://github.com/cisagov/cyhy-system/issues/59)

**Comment by dav3r** [comment]
Completed via https://github.com/cisagov/cyhy-reports/pull/76.
