### ISSUE TITLE
Use non-NVD CVSS 3 score when appropriate

### ISSUE THREAD

**Issue by dav3r** [cisagov/cyhy-system#64]
If a vulnerability finding does not have a CVE ID or its CVE ID is not found in the NVD data, then its corresponding ticket should be assigned the CVSS v3 score from the vulnerability finding source (e.g. Nessus).  If no v3 score is available, then the v2 score should be used instead.

In these cases, the CVSS version should be set to either `"3"` or `"2"` (depending on which CVSS score is available) since the exact CVSS version cannot be determined from the vulnerability finding source.

**Comment by dav3r** [comment]
@climber-girl - please confirm if the logic above works for you.  I think it makes the most sense, but please let me know if you have questions or concerns.

CC: @chelsgr, @felddy

**Comment by climber-girl** [comment]
@dav3r - I agree with the above logic! 

In other terms, we will rate the severity in a manner prioritized in the following order:
- NVD CVSSv3.1
- NVD CVSSv3.0
- NVD CVSSv2.0
- Tenable CVSSv3
- Tenable CVSSv2

As you mentioned, Tenable sourced scores do not distinguish between 3.1 or 3.0, so I am good with plain "3" and "2" for those ones.

So, if there is a CVE ID and it corresponds to something in the NVD, the cvss_version field will be one of: `[2.0, 3.0, 3.1]`, but if we are relying on Tenable's "manual" CVSS score, the cvss_version field will be either `2` or `3`.

**Comment by dav3r** [comment]
Thanks @climber-girl! 👍

**Comment by dav3r** [comment]
Completed via https://github.com/cisagov/cyhy-core/pull/69.
