### ISSUE TITLE
Add Ticket _id to Cybex's Urgent Tickets Attachments

### ISSUE THREAD

**Issue by climber-girl** [cisagov/cyhy-system#76]
# 💡 Summary #

Please add the _id associated with the tickets listed in the open/closed urgent ticket csvs that accompany the Cybex Scorecard.

## Motivation and context ##

The Cyber Directives team would like to see the unique ticket identifiers for both open and closed urgent tickets because it becomes complicated to track whether a particular vulnerability is open/closed and when it closed by just using the IP address. 

## Implementation notes ##

This should be a new first column for _id in the open/closed urgent tickets csvs.

## Acceptance criteria ##

- [ ] Unique tracking identifier is included in the open/closed urgent tickets csvs that accompany the Cybex Scorecard each week so that Cyber Directives can track which vulnerability is which over time each week.

**Comment by climber-girl** [comment]
@king-alexander or @rc-raizen, would one of you be able to help put in a PR for this issue please? I think the appropriate code can be found in [cybex_queries](https://github.com/cisagov/ncats-webd/blob/36be445cef523532bb32c29eb9565dc6f2f8e62a/ncats_webd/cybex_queries.py).

I'm hoping it might be as easy as adding `"_id",` between L247-L248 and L280-L281. `_id` may also need to be changed from `false` to `true` at L23, L112, and L183, but I'm not sure what else may need to be done.

**Comment by rc-raizen** [comment]
ready for testing
